services:
  postgres:
    image: postgres:16
    container_name: clickbeard_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clickbeard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clickbeard_net

volumes:
  pgdata:

networks:
  clickbeard_net: